config/routes.rb
Rails.application.routes.draw do
  get '/about', to: 'static_pages#about'

  root 'links#index'
 
  resources :links, only: [:index, :new, :create, :destroy] do
  	member do
      get :upvote
  end
  resources :comments, only: [:new, :create, :show, :destroy]
end

  resource :session, only: [:new, :create, :destroy]
  get '/login', to:'sessions#new', as: :login
  delete '/logout', to: 'sessions#destroy', as: :logout

  resources :users, except: [:index]

  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user, dependent: :destroy
  belongs_to :link, dependent: :destroy

  validates :body, length: {in: 2..200}
end

app/models/link.rb
class Link < ActiveRecord::Base
acts_as_votable


  belongs_to :user

  has_many :comments, dependent: :destroy

  validates :title, presence: true,
                    uniqueness: {case_sensitive: false},
                    length: {in: 5..150}
  validates :url,   presence: true,
                    uniqueness: {case_sensitive: false},
                    length: {in: 5..150}

  validates :url, :format => URI::regexp(%w(http https))   

       

end

app/models/user.rb
class User < ActiveRecord::Base
	include Gravtastic
    gravtastic
	has_secure_password

	acts_as_voter

	def to_param
		username
	end

	has_many :links, dependent: :destroy

	validates :username, presence: true,
	                     uniqueness: {case_sensitive: false},
	                     length: {in: 4..12},
	                     format: {with: /\A[a-zA-Z][a-zA-Z0-9_-]*\Z/}
	validates :first_name, presence: true
	validates :last_name, presence: true
	validates :email, presence: true,
	                  uniqueness: {case_sensitive: false},
	                  email: true
	validates :password, presence: true,
	                     length: {minimum: 6} 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  private
  def current_user
  	@current_user = User.find(session[:user_id]) if session[:user_id]
  end
  def signed_in?
  	current_user
  end
  helper_method :signed_in?, :current_user
def validate_user!
	unless signed_in?
		redirect_to login_path
	end
end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :validate_user!, only: [:create]
	def new
		@link = Link.find(params[:link_id])
		@comment = @link.comments.new
		@comment.user = current_user
	end
	def create
		@link = Link.find(params[:link_id])
		@comment = @link.comments.new(comment_params)
		@comment.user = current_user
		if @comment.save
			redirect_to new_link_comment_path
		else
			render :new
		end
	end
	
	private
	def comment_params
		params.require(:comment).permit!
	end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
	before_action :validate_user!, only: [:new, :create]
	def index
		@links = Link.paginate(:page => params[:page], :per_page => 10).order('created_at DESC')
		end
	def new
		if :validate_user!
		@link = Link.new
	else
		flash[:error] = "Please login to share a link."
	end
	end
	def create
		@link = current_user.links.create(params.require(:link).permit!)
		if @link.save
			redirect_to root_url
		else
			render :new
		end
	end
	def show
		@link = Link.find(params[:id])
	end
	def upvote
    @link = Link.find(params[:id])
    @link.liked_by current_user
    redirect_to :back
end	


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
  	user = User.find_by_username(params[:sessions][:user_name])

  	if user && user.authenticate(params[:sessions][:password])
  		session[:user_id] = user.id
  		redirect_to root_url
  	else
  		flash.now[:error] = "Invalid Username or Password, Please try again."
  		render :new
  	end
  end

  def destroy
  	session[:user_id] = nil
  	redirect_to root_url
end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :select_user, only: [:show, :edit, :update, :destroy]
before_action :validate_permission!, only: [:edit, :update, :destroy]
	
	def new
		@user = User.new
	end
	def create
		@user = User.new(user_params)
		if @user.save
			redirect_to new_session_path
		else
			render :new
		end
	end
	def show
	end
	def edit
	end
	def update
		update_params = user_params
		if update_params.has_key?(:password)
		   update_params.delete([:password, :password_confirmation])
		end
		if @user.update(update_params)
			redirect_to root_url
		else
			render :edit
		end
	end
	def destroy
		session[:user_id] = nil
		@user.destroy
		redirect_to root_url
		end
		private
		def user_params
			params.require(:user).permit!
		end
		def select_user
			@user = User.find_by_username(params[:id])
			rescue ActiveRecord::RecordNotFound
  redirect_to(root_url, :notice => 'Record not found')
		end

		def validate_permission!
	    unless current_user == @user
		redirect_to root_url, alert: 'Nope!'
	end
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<% if comment.body != nil %>
	<div class="comment"><hr>
		<p><%= comment.body %></p>
		<small class="details">
			submitted by <%= link_to comment.user.username, comment.user %>
			<%= time_ago_in_words comment.created_at %> ago
<% end %>
</small></hr>

app/views/comments/new.html.erb
<p>
<h4 class="text-center"><%= link_to @link.title, @link.url %></h4><hr>
<%= form_for [@link, @comment] do |f| %>
<div class="row">
<div class="large-12 columns">
<label>Add Comment</label>
<%= f.text_area :body %>
<%= f.submit "Add Comment", class: 'small button right' %>
</div>
<% end %>
</p>

<%= render @link.comments %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Clone News" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
  	<%= render partial: "shared/top_bar" %>
  	<% if flash[:error] %><div data-alert class="alert-box secondary">
  <%= flash[:error] %>
  <a href="#" class="close">&times;</a>
  <% end %>
</div>

  	<%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/links/index.html.erb
<p>
<% @links.each do |link| %>
<div class="text-center">
<div class="row">
	<div class="large-8 large-centered columns">
    <h5><%= link_to link.title, link.url %><blockquote><%= URI::Parser.new.parse(link.url).host %></blockquote></h5>
	<small class="details"><%= link.votes_for.size %> Likes | <%= link_to "Like", upvote_link_path(link)%> |</small>
		<small class="details">submitted by <%= link_to link.user.username, user_path(link.user) %>
		<%= time_ago_in_words link.created_at %> ago, <%= link_to "comments", new_link_comment_path(link) %> <%= link.comments.size %>
	</small>
</div>
</div>
</div>
</p>
<div class="large-10 large-centered columns"><hr/></div>
<% end %>
<div class="text-center">
<p><%= will_paginate @links, :page_links => false %></p>
</div>

app/views/links/new.html.erb
<%= render partial: "shared/link_error" %>
<p>
<div class="row">
<%= form_for @link do |f| %>
<div class="large 6 columns large centered panel radius">
		<%=f.label :title, placeholder: 'Title' %>
		<%= f.text_field :title %>
		<%=f.label :url, placeholder: 'url' %>
		<%= f.url_field :url, placeholder: 'http//' %>
	</div>
	<div class="large-6 columns">
		<%= f.submit "    Share    ", class: 'medium button right' %>
	</div>
</div>
<% end %>
</p>

app/views/links/show.html.erb
<p>
<%= @link.title %><br>
<%= @link.url %>
</p>
  

app/views/shared/_link_error.html.erb
<% if @link.errors.any? %>
<div data-alert class="alert-box">
<% @link.errors.full_messages.each do |message| %>
<li><%= message %></li>
<% end %>
<a href="#" class="close">&times;</a>
</div>
<% end %>

app/views/shared/_top_bar.html.erb
<div class="contain-to-grid">
  		<nav class="top-bar">
  			<ul class="title-area">
  				<li class="name">
  					<strong><h1><a href='#'><strong>Clone News</strong></a></h1>
  				</li>
        </ul>
        <section class="top-bar-section">
  		<ul class="left">
  			<li><%= link_to "Share a link", new_link_path %></li>
  		</ul>
  		</section>
  		<section class="top-bar-section">
        <ul class="right">
        <% if signed_in? %>
            <li><%= link_to "Edit Profile", edit_user_path(current_user) %>  
  			<li><%= link_to current_user.username, user_path(current_user) %></li>
  			<li><%= link_to "Logout", logout_path, method: :delete %>
  				
  			<% else %>
  			<li><%= link_to "Sign Up", new_user_path %></li>
  			<li><%= link_to "Login", login_path %></li>
  			<% end %>
  		</ul>
  		</section>
 
  </nav>
  	</div>

app/views/shared/_user_error.html.erb
<% if @user.errors.any? %>
<div data-alert class="alert-box">
<% @user.errors.full_messages.each do |message| %>
<li><%= message %></li>
<% end %>
<a href="#" class="close">&times;</a>
</div>
<% end %>

app/views/static_pages/about.html.erb
<p>
<div class="row">
<p>
	<strong>Clone News is the meet up place for the rubyists and the people who are passionate about programming.</strong>
</p>
<p>
	<u>Simply share link, or click to explore.</u>
</p>
</div>
</p>

app/views/users/edit.html.erb
<p>
<%= form_for @user do |f| %>
<div class="row">
<div class="large-12 columns">
<%= f.label :about %>
<%= f.text_field :about, placeholder: "Write something about you" %>
</div>
<div class="large-6 columns">
<%= f.label :first_name %>
<%= f.text_field :first_name %>
</div>
<div class="large-6 columns">
<%= f.label :last_name %>
<%= f.text_field :last_name%>
</div>
<div class="large-12 columns">
<%= f.label :username %>
<%= f.text_field :username %>
</div>
<div class="large-12 columns">
<%= f.label :email %>
<%= f.email_field :email %>
</div>
<div class="large-12 columns">
<%= f.label :password %>
<%= f.password_field :password %>
</div>
<div class="large-12 columns">
<%= f.label :password_confirmation %>
<%= f.password_field :password_confirmation %>
</div>
<div class="large-12 columns">
<%= f.submit "    Edit    ", class: 'medium button right' %>
</div>
</div>
<% end %>
</p>

<div class="row"><%= link_to "Delete My Account", @user, method: :delete, data: {confirm: "Are you sure?"}, class: 'small button alert' %></div>

app/views/users/new.html.erb
<%= render partial: "shared/user_error" %>
<p>
<%= form_for @user do |f| %>
<div class="row">
<div class="large-6 columns">
<%= f.label :first_name %>
<%= f.text_field :first_name %>
</div>
<div class="large-6 columns">
<%= f.label :last_name %>
<%= f.text_field :last_name%>
</div>
<div class="large-12 columns">
<%= f.label :username %>
<%= f.text_field :username %>
</div>
<div class="large-12 columns">
<%= f.label :email %>
<%= f.email_field :email %>
</div>
<div class="large-12 columns">
<%= f.label :password %>
<%= f.password_field :password %>
</div>
<div class="large-12 columns">
<%= f.label :password_confirmation %>
<%= f.password_field :password_confirmation %>
</div>
<div class="large-12 columns">
<%= f.submit "Sign Up", class: 'medium button right' %>
</div>
</div>
<% end %>
</p>

app/views/users/show.html.erb
<p>
<div class="row">
	<div class="text-center">
<div class="large-3 large-centered columns"><%= image_tag @user.gravatar_url, class: 'profile-image' %></div>
</div>
<hr/>
</p>
<p>
<div class="text-center">
<h3><div class="large-3 large-centered columns"><%= @user.username %></div></h3>
<h3><div class="large-3 large-centered columns"><%= @user.about %></div></h3>
</div>
</p>